# Generated by Django 4.0.3 on 2022-03-27 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 42, 6, 205406, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 42, 6, 205406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 42, 6, 204405, tzinfo=utc)),
        ),
    ]
