# Generated by Django 4.0.3 on 2022-04-09 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_employee_address_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 25, 28, 580557, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 25, 28, 581554, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 25, 28, 580557, tzinfo=utc), null=True),
        ),
    ]
