# Generated by Django 4.0.3 on 2022-04-10 04:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_employee_created_at_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 23, 21, 234646, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 23, 21, 235647, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 23, 21, 233645, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Advertence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 23, 21, 402697, tzinfo=utc), null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('note', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.manager')),
            ],
        ),
    ]
