# Generated by Django 4.0.3 on 2022-04-10 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_employee_created_at_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 43, 45, 361600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 43, 45, 302599, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 43, 45, 303599, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 4, 43, 45, 301599, tzinfo=utc), null=True),
        ),
    ]
