# Generated by Django 4.0.3 on 2022-05-14 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_presencecontrol_payment_alter_advertence_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presencecontrol',
            old_name='is_present_afternoon',
            new_name='presence_afternoon',
        ),
        migrations.RenameField(
            model_name='presencecontrol',
            old_name='is_present_morning',
            new_name='presence_morning',
        ),
        migrations.AlterField(
            model_name='advertence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 38, 47, 855928, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 38, 47, 783123, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 38, 47, 785119, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='merit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 38, 47, 885850, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 38, 47, 783123, tzinfo=utc), null=True),
        ),
    ]
