# Generated by Django 4.0.3 on 2022-05-15 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_is_present_afternoon_presencecontrol_presence_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 1, 27, 11, 787750, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 1, 27, 11, 719183, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 1, 27, 11, 720180, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='merit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 1, 27, 11, 809157, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 1, 27, 11, 718185, tzinfo=utc), null=True),
        ),
    ]
