# Generated by Django 4.0.5 on 2022-06-04 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_advertence_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 49, 57, 931791, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 49, 57, 898791, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 49, 57, 900792, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='merit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 49, 57, 953791, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 49, 57, 898791, tzinfo=utc), null=True),
        ),
    ]
