# Generated by Django 4.0.3 on 2022-03-27 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_employee_created_at_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 43, 23, 145266, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 43, 23, 146264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 2, 43, 23, 145266, tzinfo=utc)),
        ),
    ]
