# Generated by Django 4.0.3 on 2022-04-09 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_employee_created_at_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 27, 6, 686380, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 27, 6, 687385, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 20, 27, 6, 686380, tzinfo=utc), null=True),
        ),
    ]
