# Generated by Django 4.0.3 on 2022-05-14 00:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_advertence_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencecontrol',
            name='payment',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 34, 23, 496404, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 34, 23, 424596, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 34, 23, 426594, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 34, 23, 423598, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 0, 34, 23, 519342, tzinfo=utc), null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('note', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.manager')),
            ],
        ),
    ]
